CREATE TABLE PRODUTOS
(
CODIGO VARCHAR(10) NOT NULL
,DESCRITOR VARCHAR(100) NULL
,SABOR VARCHAR(50) NULL
,TAMANHO VARCHAR(50) NULL
,EMBALAGEM VARCHAR(50) NULL
,PRECO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO));
------------------------------------------------------
CREATE TABLE VENDEDORES
(MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
COMISSAO FLOAT NULL,
DATA_ADIMISSAO DATE NULL,
FERIAS INTEGER NULL,
PRIMARY KEY (MATRICULA));

ALTER TABLE VENDEDORES
RENAME COLUMN DATA_ADIMISSAO TO DATA_ADMISSAO;
------------------------------------------------------
CREATE TABLE CLIENTES
(CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(100) NULL,
ENDERECO VARCHAR(150) NULL,
BAIRRO VARCHAR(50) NULL,
CIDADE VARCHAR(50) NULL,
ESTADO VARCHAR(50) NULL,
CEP VARCHAR(8) NULL,
DATA_NASCIMENTO DATE NULL,
IDADE INTEGER NULL,
SEXO VARCHAR(1) NULL,
LIMITE_CREDITO FLOAT NULL,
VOLUME_COMPRA FLOAT NULL,
PRIMEIRA_COMPRA INTEGER NULL,
PRIMARY KEY (CPF));

------------------------------------------------------
CREATE TABLE VENDAS
(
NUMERO VARCHAR(5) NOT NULL
,DATA_VENDA DATE NULL
,CPF VARCHAR(11) NOT NULL
,MATRICULA VARCHAR(5) NOT NULL
,IMPOSTO FLOAT NULL
,PRIMARY KEY (NUMERO)
);

ALTER TABLE VENDAS
ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);

ALTER TABLE VENDAS
ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);

alter table "SYSTEM"."VENDAS" rename to NOTAS;

------------------------------------------------------
CREATE TABLE ITENS_NOTAS
(NUMERO VARCHAR(5) NOT NULL, -- FK_NOTAS
CODIGO VARCHAR(10) NOT NULL, -- FK_PRODUTO
QUANTIDADE INTEGER NULL,
PRECO FLOAT NULL,
PRIMARY KEY (NUMERO,CODIGO));

ALTER TABLE ITENS_NOTAS
ADD CONSTRAINT FK_NOTAS
FOREIGN KEY (NUMERO) REFERENCES NOTAS (NUMERO);

ALTER TABLE ITENS_NOTAS
ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO) REFERENCES PRODUTOS (CODIGO);
