INSERT INTO TB_EMPRESA (nome_empresa, cod_empresa) VALUES ('EMPRESA E0001','E0001');
INSERT INTO TB_EMPRESA (nome_empresa, cod_empresa) VALUES ('EMPRESA E0002','E0002');

SELECT * FROM TB_EMPRESA;

-- *******************************************************************************

SELECT * FROM TB_DEPARTAMENTO;

--esta é a melhor maneira de inserir varias linhas no pl/sql
INSERT ALL
INTO TB_DEPARTAMENTO VALUES ('D0001', 'DEPARTAMENTO D0001', 'CAMPINAS', 'E0001')
INTO TB_DEPARTAMENTO VALUES ('D0002', 'DEPARTAMENTO D0002', 'CAMPO GRANDE', 'E0001')
INTO TB_DEPARTAMENTO VALUES ('D0003', 'DEPARTAMENTO D0003', 'CAMPINAS', 'E0001')
INTO TB_DEPARTAMENTO VALUES ('D0004', 'DEPARTAMENTO D0004', 'CAMPO GRANDE', 'E0001')
SELECT * FROM DUAL;

/**
-- esta maneira nao funciona aqui no pl/sql. Mas fuinciona mo mysql
INSERT INTO TB_DEPARTAMENTO (COD_DEPARTAMENTO, NOME_DEPARTAMENTO, CIDADE, COD_EMPRESA) VALUES
('D0005', 'DEPARTAMENTO D0005', 'CAMPINAS', 'E0001'),
('D0006', 'DEPARTAMENTO D0006', 'CAMPO GRANDE', 'E0002'),
('D0007', 'DEPARTAMENTO D0007', 'CAMPINAS', 'E0001'),
('D0008', 'DEPARTAMENTO D0008', 'CAMPO GRANDE', 'E0002');
**/